routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
});



Route::resource('clients', 'ClientController', ['only' => ['index', 'create', 'store', 'show', 'destroy']])->middleware('role:administrator');
Route::get('/clientinfo', 'ClientController@show_detailed_info')->middleware('role:administrator');
Route::resource('users', 'UserController', ['only' => ['index', 'create', 'store','destroy']])->middleware('role:administrator');
Route::resource('assignments', 'AssignmentController', ['only' => ['index', 'create', 'store', 'show', 'destroy']])->middleware('role:administrator');


Route::get('/projects','ProjectController@index')->middleware('role:administrator|user');
Route::get('/projects/create','ProjectController@create')->middleware('role:administrator')
														 ->name('projects.create');
Route::get('/projects/{id}', 'ProjectController@show')->middleware('role:administrator')->name('projects.show');

Route::post('/projects','ProjectController@store')->middleware('role:administrator|user');
Route::get('/allprojects','ProjectController@indexAll')->middleware('role:administrator');
Route::get('/projects/{id}/delete',      'ProjectController@destroy')->middleware('role:administrator');
Route::get('/projectinfo', 'ProjectController@show_detailed_info')->middleware('role:administrator');
Route::get('/projectdetails/{id}','ProjectController@show_user_info')->middleware('role:administrator|user');


Route::resource('reports', 'ReportController')->middleware('role:administrator|user');
Route::get('/reports', 'ReportController@show_reports_period')->middleware('role:administrator|user')->name('reports-bydate.index');
// Route::get('reports/{id}/edit', 'ReportController@edit')->middleware('role:administrator|user')->name('reports.edit');



//Route::get('/clients/create', 'ClientController@create');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    protected $fillable = ['name', 'description', 'date_start', 'date_end', 'id_cliente'];
    
    public function projects() 
    {	
		return $this->belongsTo('App\Client');
	}

}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Validator;
use Carbon\Carbon;

use App\Project;
use Auth;
use App\Client;

class ProjectController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Hsttp\Response
     */
    public function index()
    {
      
        $user_id = Auth::id();
        $projects = DB::table('projects')
                    ->select('projects.name as name', 'projects.id as id', 'projects.description as description')
                    ->join('assignments', 'projects.id', '=', 'assignments.id_project')
                    ->where('assignments.id_user', '=', $user_id)
                    ->distinct()->get();


        return view('projects.index', compact('projects'));
    }

    // Display all projects
     public function indexAll()
    {
        $projects = DB::table('projects')
                    ->select('projects.name as name', 'projects.id as id', 'projects.description as description', 'clients.ragione_sociale as client', 'clients.id as client_id' )
                    ->join('clients', 'projects.id_cliente', '=', 'clients.id')
                    ->distinct()->get();
        return view('projects.adminIndex', compact('projects'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $clients = Client::all();

        return view('projects.create', compact('clients'));

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input = $request->all();

        $validator = Validator::make($input, [
            'name'          => 'required|max:100',
            'description'   => 'max:255',
            'date_start'    => 'date|after:yesterday',
            'date_end'      => 'date|after:date_start|nullable',
            'id_cliente'    => 'required|exists:clients,id',
        ]);

        if ($validator->fails()) {
            return redirect('projects/create')
                ->withErrors($validator)
                ->withInput();
        }

        $project = new Project;
        $project->name        = $request->input('name');
        $project->description = $request->input('description');
        $project->date_start  = $request->input('date_start');
        $project->date_end    = $request->input('date_end');
        $project->id_cliente  = $request->input('id_cliente');
        $project->save();

        return redirect('/allprojects');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $date_from = new Carbon('first day of this month');
        $date_to   = new Carbon('last day of this month');
        

        $elemento = Project::find($id);
        $client = Client::find($elemento->id_cliente);
        $team = DB::table('users')
                        ->select('users.name as name', 'users.surname as surname', 'users.id as id', 'assignments.position as position', 'assignments.id as assignment_id')
                        ->join('assignments', 'users.id', '=', 'assignments.id_user')
                        ->where('assignments.id_project', '=', $id)->get();
        $total_time_spent = DB::table('reports')
                        ->where('id_project', '=', $id)->whereBetween('date', array($date_from, $date_to))
                        ->sum('ore');
        $expenses = DB::table('reports')
                     ->join('assignments', 'reports.id_assignment', '=', 'assignments.id')   
                    ->where('reports.id_project', '=', $id)->whereBetween('date', array($date_from, $date_to))
                    ->sum(\DB::raw('assignments.internal_rate * ore'));
        $income = DB::table('reports')
                    ->join('assignments', 'reports.id_assignment', '=', 'assignments.id')
                    ->where('reports.id_project', '=', $id)->whereBetween('date', array($date_from, $date_to))
                    ->sum(\DB::raw('assignments.external_rate * ore'));

        return view('projects.show', compact('elemento', 'client', 'team', 'total_time_spent', 'income', 'expenses'));
    }

    public function show_detailed_info(Request $request){
        $msg  = $request->query('message');
        $date_from = $msg['date_from'];
        $date_to    = $msg['date_to'];
        $project_id = $msg['project_id'];

        $total_time_spent = DB::table('reports')
                    ->where('id_project', '=', $project_id)->whereBetween('date', array($date_from, $date_to))
                    ->sum('ore');
        $total_personell_expenses = DB::table('reports')
                    ->join('assignments', 'reports.id_assignment', '=', 'assignments.id')
                    ->where('reports.id_project', '=', $project_id)->whereBetween('date', array($date_from, $date_to))
                    ->sum(\DB::raw('assignments.internal_rate * ore'));
        $total_personell_profit = DB::table('reports')   
                    ->join('assignments', 'reports.id_assignment', '=', 'assignments.id')
                    ->where('reports.id_project', '=', $project_id)->whereBetween('date', array($date_from, $date_to))
                    ->sum(\DB::raw('assignments.external_rate * ore'));

        $to = new Carbon($date_to);
        $to = $to->format('d F Y');
        $from = new Carbon($date_from);
        $from = $from->format('d F Y');
        

     return response()->json(array('total_time_spent'=> $total_time_spent, 'date_from' => $from, 'date_to' => $to, 'income' => $total_personell_profit, 'expenses' => $total_personell_expenses), 200);
        
    }

    public function show_user_info($id){  
        $date_from = new Carbon('first day of this month');
        $date_to   = new Carbon('last day of this month');
        $user_id = Auth::id();
        $elemento = Project::find($id);
       
        $reports = DB::table('reports')
                    ->select('reports.id as id', 'assignments.position as position', 
                             'reports.ore as hours', 'reports.note as note', 
                             'reports.date as date')
                    ->join('assignments', 'reports.id_assignment', '=', 'assignments.id')
                    ->where('reports.id_user', '=', $user_id)
                    ->where('assignments.id_project', '=', $id)->get();
        $ore_totale = DB::table('reports')
                    ->join('assignments', 'reports.id_assignment', '=', 'assignments.id')
                    ->where('reports.id_user', '=', $user_id)
                    ->where('assignments.id_project', '=', $id)->sum('ore');

        return view('projects.usershow', compact('elemento', 'reports', 'ore_totale'));     
      
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $elemento = Project::find($id);
        $elemento->delete();
        return redirect('/allprojects');
    }
}

resources/views/projects/adminIndex.blade.php
@extends ('layouts.app')

@section('content')
 <div class="flex-container">
 <div class="columns m-t-10">
   <div class="column">
	<h1 class="title">Projects</h1>
</div>
	 <div class="column">
          <a href="{{route('projects.create')}}" class="button is-primary is-pulled-right"><i class="fa fa-user-plus m-r-10"></i> Add New Project</a>
        </div>
        <div class="column">
          <a href="{{route('assignments.create')}}" class="button is-primary is-pulled-right"><i class="fa fa-user-plus m-r-10"></i> Add Assignment</a>
        </div>
</div>
	      <hr class="m-t-0">

	    <div class="card">
        <div class="card-content">
          <table class="table is-narrow ">
            <thead>
              <tr>
                <th>Project name</th>
                <th>Description</th>
                <th>Company</th>
                <th>Action</th>
                <th></th>
              </tr>
            </thead>

            <tbody>
              
				@foreach ($projects as $project)
                <tr>
                  <td><a class="button is-outlined" href="{{route('projects.show', $project->id)}}">{{$project->name}}</a></td>
                  <td>{{$project->description}}</td>
                  <td><a class="button is-outlined" href="{{route('clients.show', $project->client_id)}}">{{$project->client}}</a></td>
                  <td> <a class="btn btn-danger btn-xs" href="{{  URL::action('ProjectController@destroy', $project->id) }}" >Delete</a></td>
              </tr>
              @endforeach
            </tbody>
          </table>
        </div>
	</div>
</div>
@endsection

resources/views/projects/create.blade.php
@extends ('layouts.app')

@section('content')
    <div class="row">
        <div class="col-md-6">
            <p class="h3">New project?</p>

            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            {!! Form::open(['action' => 'ProjectController@store', 'method' => 'POST', 'enctype' => 'multipart/form-data']) !!}
                <div class="form-group">
                    {{Form::label('name', 'Title')}}
                    {{Form::text('name', '', ['class' => 'form-control'])}}
                </div>
                <div class="form-group">
                    {{Form::label('description', 'Description')}}
                    {{Form::textarea('description', '', ['class' => 'form-control', ])}}
                </div>
                <div class="form-group">
                     {{Form::label('date_start', 'Start')}}
                    {{Form::date('date_start', '', ['class' => 'form-control'])}}
                </div>
                <div class="form-group">
                     {{Form::label('date_end', 'End')}}
                    {{Form::date('date_end', '', ['class' => 'form-control'])}}
                </div>   

                <div class="form-group">
                    {{Form::label('id_cliente', 'Client')}}
                    
                    <select class="form-control" name="id_cliente">
                        @foreach ($clients as $client)
                        <option value="{{ $client->id }}">{{ $client->ragione_sociale }}</option>
                        @endforeach
                    </select>
                </div>     
         {{Form::submit('Submit', ['class'=>'btn btn-primary'])}}
        {!! Form::close() !!}
        </div>
    </div>
@endsection

resources/views/projects/index.blade.php
@extends ('layouts.app')

@section('content')

<h1 class="title">Your projects</h1>
<br />
<div class="row">
    <div class="col-md-12">
        @if (count($projects) > 0)
        <div class="card">
        <div class="card-content">
            <table class="table table-bordered ">
                <thead>
                    <tr>
                        <th scope="col">Project Title</th>
                        <th scope="col">Description</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($projects as $project)
                    <tr>
                        <td><a class="button is-outlined" href="{{  URL::action('ProjectController@show_user_info', $project->id) }}">{{$project->name}}</a></td>
                        <td>{{ $project->description }}</td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
            @else 
                <p>There are not projects yet :)</p>
            @endif
    </div>        
</div>
@endsection

resources/views/projects/show.blade.php
@extends('layouts.app')


@section('content')

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <div class="row">
        <div class="col-md-12">
            <p class="h3">{{ $elemento->name }} </p>

        </div>
    </div>
    <div class="card">
        <div class="card-content">
          <table class="table is-narrow">
              <tr>
                <th style="width: 17%">Project description</th>
                <th>{{$elemento->description}}</th>
              </tr>
              <tr>
                <th>Client</th>
                <th><a class="button is-outlined" href="{{route('clients.show', $client->id)}}">{{$client->ragione_sociale}}</a></th>
              </tr>
                <tr>
                <th>Contact person</th>
                <th> {{$client->nome_referente}} {{$client->cognome_referente}} : {{$client->email}}</th>
              </tr>
              </tr>
                <tr>
                <th>Team</th>
                <th> 
                    @foreach ($team as $team_member)
                         {{$team_member->name}} {{$team_member->surname}} as {{$team_member->position}} 
                                <form
                                action="{{ route('assignments.destroy', $team_member->assignment_id) }}"
                                method="POST"
                                >
                      <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                    {{ method_field('DELETE') }}
                      {{ csrf_field()}}
                    </form>
                    @endforeach
                    </th>
              </tr>
          </table>
</div>
</div>

 <hr class="m-t-0">
<h5>Info for period from <b id="from">{{Carbon\Carbon::now()->startOfMonth()->format('d F Y')}} </b> to <b id="to">{{Carbon\Carbon::now()->endOfMonth()->format('d F Y')}}</b> </h5>
        <div class="card">
        <div class="card-content">
          <table class="table is-narrow">
            <thead>
              <tr>
                <th>Total time spent</th>
                <th>Income</th>
                <th>Personnel expenses</th>
              </tr>
            </thead>
            <tbody>
                <tr>
                  <td id="total_time">{{$total_time_spent}}</td>
                  <td id="income">{{$income. '  €'}}</td>
                  <td id="expenses">{{$expenses. '  €'}}</td>
              </tr>
            </tbody>
          </table>
        </div>
    </div>
<br>
<h5> Change period: </h5>

              <div class="form-group">
                     {{Form::label('date_from', 'Start')}}
                    {{Form::date('date_from', '', ['class' => 'form-control'])}}
                </div>
                <div class="form-group">
                     {{Form::label('date_to', 'End')}}
                    {{Form::date('date_to', '', ['class' => 'form-control'])}}
                </div>   
                <button type="button" class="btn btn-primary" id="getRequest">Save</button>
 
        

<script type="text/javascript">
$.ajaxSetup({
    headers: {
        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
    }
});

    $('document').ready(function(){
        console.log('Ciao');

        $('#getRequest').bind('click', function(event) {
            event.preventDefault(); // Fermo l'azione 

            var button = $(this);
       
            var Jdata = {
              date_from: $('#date_from').val(),
              date_to: $('#date_to').val(),
              project_id: {{$elemento->id}},
            };

            console.log(Jdata);
            $.ajax({
                url: "/projectinfo/", 
                //url: url,
                type: "GET",
                dataType: "json",
                data: {
                  'message': Jdata,
                  '_token': $('meta[name="csrf-token"]').attr('content')},
                success: function(response) {
                  // $("#exampleModal").modal("hide");
                    console.log(response);
                    $("#from").text(response.date_from);
                    $("#to").text(response.date_to);
                    $("#total_time").text(response.total_time_spent);
                    $("#income").text(response.income);
                    $("#expenses").text(response.expenses);
                    $("#date_to").val('');
                    $("#date_from").val('');
                    // $(button).parents('tr').fadeOut();
                }, 
                error: function(response, stato) {
                  //alert("Data is incorrect, please try again.");
                    console.log(response);
                }
            });

        });
    });
</script>

@endsection

resources/views/projects/usershow.blade.php
@extends('layouts.app')


@section('content')

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <div class="row">
        <div class="col-md-12">
            <p class="h3">{{ $elemento->name }} </p>
        </div>
    </div>
            <hr class="m-t-0">

    <h5>Total time: {{$ore_totale}} h</h5>
        <div class="card">
        <div class="card-content">
          <table class="table is-narrow">
            <thead>
              <tr>
                <th>Position</th>
                <th>Work description</th>
                <th>Date</th>
                <th>Hours</th>
                <th></th>
              </tr>
            </thead>

            <tbody>
              
                @foreach ($reports as $report)
                <tr>
                  <td>{{$report->position}}</td>
                  <td>{{$report->note}}</td>
                  <td>{{$report->date}}</td>
                  <td>{{$report->hours}}</a></td>
                  <td> 
                  <a class="btn btn-danger btn-xs" onclick="event.preventDefault(); document.getElementById('delete-report').submit();">Delete</a>
                    <form id="delete-report"
                                action="{{ route('reports.destroy', $report->id) }}"
                                method="POST"
                                style="display: none;"
                    >
                        {{ method_field('DELETE') }}
                      {{ csrf_field() }}
                    </form></td>
              </tr>
              @endforeach
            </tbody>
          </table>
        </div>
    </div>
</div>
</div>

@endsection